export const STATUS_PALLETTES = {
    limeSubtlest: '#efffd6',
    limeSubtlestHovered: '#d3f1a7',
    limeSubtlestPressed: '#bde97c',
    limeSubtler: '#d3f1a7',
    limeSubtlerHovered: '#bde97c',
    limeSubtlerPressed: '#b3df72',
    limeSubtle: '#94c748',
    limeSubtleHovered: '#b3df72',
    limeSubtlePressed: '#bde97c',
    limeBolder: '#5b7f24',
    limeBolderHovered: '#4c6b1f',
    limeBolderPressed: '#3f5224',

    redSubtlest: '#ffeceb',
    redSubtlestHovered: '#ffd5d2',
    redSubtlestPressed: '#ffb8b2',
    redSubtler: '#ffd5d2',
    redSubtlerHovered: '#ffb8b2',
    redSubtlerPressed: '#fd9891',
    redSubtle: '#f87168',
    redSubtleHovered: '#fd9891',
    redSubtlePressed: '#ffb8b2',
    redBolder: '#c9372c',
    redBolderHovered: '#ae2e24',
    redBolderPressed: '#872821',

    orangeSubtlest: '#fff5db',
    orangeSubtlestHovered: '#fce4a6',
    orangeSubtlestPressed: '#fbd779',
    orangeSubtler: '#fce4a6',
    orangeSubtlerHovered: '#fbd779',
    orangeSubtlerPressed: '#fbc828',
    orangeSubtle: '#fca700',
    orangeSubtleHovered: '#fbc828',
    orangeSubtlePressed: '#fbd779',
    orangeBolder: '#bd5b00',
    orangeBolderHovered: '#9e4c00',
    orangeBolderPressed: '#7a3b00',

    yellowSubtlest: '#fef7c8',
    yellowSubtlestHovered: '#f5e989',
    yellowSubtlestPressed: '#efdd4e',
    yellowSubtler: '#f5e989',
    yellowSubtlerHovered: '#efdd4e',
    yellowSubtlerPressed: '#eed12b',
    yellowSubtle: '#eed12b',
    yellowSubtleHovered: '#ddb30e',
    yellowSubtlePressed: '#efdd4e',
    yellowBolder: '#946f00',
    yellowBolderHovered: '#7f5f01',
    yellowBolderPressed: '#614a05',

    greenSubtlest: '#dcfff1',
    greenSubtlestHovered: '#baf3db',
    greenSubtlestPressed: '#97edc9',
    greenSubtler: '#baf3db',
    greenSubtlerHovered: '#97edc9',
    greenSubtlerPressed: '#7ee2b8',
    greenSubtle: '#4bce97',
    greenSubtleHovered: '#7ee2b8',
    greenSubtlePressed: '#97edc9',
    greenBolder: '#1f845a',
    greenBolderHovered: '#216e4e',
    greenBolderPressed: '#19573d',

    tealSubtlest: '#e7f9ff',
    tealSubtlestHovered: '#c6edfb',
    tealSubtlestPressed: '#b1e4f7',
    tealSubtler: '#c6edfb',
    tealSubtlerHovered: '#b1e4f7',
    tealSubtlerPressed: '#9dd9ee',
    tealSubtle: '#6cc3e0',
    tealSubtleHovered: '#9dd9ee',
    tealSubtlePressed: '#b1e4f7',
    tealBolder: '#227d9b',
    tealBolderHovered: '#206a83',
    tealBolderPressed: '#1a5265',

    blueSubtlest: '#e9f2fe',
    blueSubtlestHovered: '#cfe1fd',
    blueSubtlestPressed: '#adcbfb',
    blueSubtler: '#cfe1fd',
    blueSubtlerHovered: '#adcbfb',
    blueSubtlerPressed: '#8fb8f6',
    blueSubtle: '#669df1',
    blueSubtleHovered: '#8fb8f6',
    blueSubtlePressed: '#adcbfb',
    blueBolder: '#1868db',
    blueBolderHovered: '#1558bc',
    blueBolderPressed: '#144794',

    purpleSubtlest: '#f8eefe',
    purpleSubtlestHovered: '#eed7fc',
    purpleSubtlestPressed: '#e3bdfa',
    purpleSubtler: '#eed7fc',
    purpleSubtlerHovered: '#e3bdfa',
    purpleSubtlerPressed: '#d8a0f7',
    purpleSubtle: '#c97cf4',
    purpleSubtleHovered: '#d8a0f7',
    purpleSubtlePressed: '#e3bdfa',
    purpleBolder: '#964ac0',
    purpleBolderHovered: '#803fa5',
    purpleBolderPressed: '#673286',

    magentaSubtlest: '#ffecf8',
    magentaSubtlestHovered: '#fdd0ec',
    magentaSubtlestPressed: '#fcb6e1',
    magentaSubtler: '#fdd0ec',
    magentaSubtlerHovered: '#fcb6e1',
    magentaSubtlerPressed: '#f797d2',
    magentaSubtle: '#e774bb',
    magentaSubtleHovered: '#f797d2',
    magentaSubtlePressed: '#fcb6e1',
    magentaBolder: '#ae4787',
    magentaBolderHovered: '#943d73',
    magentaBolderPressed: '#77325b',

    graySubtlest: '#f0f1f2',
    graySubtlestHovered: '#dddee1',
    graySubtlestPressed: '#b7b9be',
    graySubtler: '#dddee1',
    graySubtlerHovered: '#b7b9be',
    graySubtlerPressed: '#8c8f97',
    graySubtle: '#8c8f97',
    graySubtleHovered: '#b7b9be',
    graySubtlePressed: '#dddee1',
    grayBolder: '#6b6e76',
    grayBolderHovered: '#505258',
    grayBolderPressed: '#3b3d42',
};

export const STATUS_PALETTE_SOLID = [
    // subtlest
    'limeSubtlest', 'redSubtlest', 'orangeSubtlest',
    'yellowSubtlest', 'greenSubtlest', 'tealSubtlest',
    'blueSubtlest', 'purpleSubtlest', 'magentaSubtlest',
    'graySubtlest',
    // subtler
    'limeSubtler', 'redSubtler', 'orangeSubtler',
    'yellowSubtler', 'greenSubtler', 'tealSubtler',
    'blueSubtler', 'purpleSubtler', 'magentaSubtler',
    'graySubtler',
    // subtle
    'limeSubtle', 'redSubtle', 'orangeSubtle',
    'yellowSubtle', 'greenSubtle', 'tealSubtle',
    'blueSubtle', 'purpleSubtle', 'magentaSubtle',
    'graySubtle',
    // bolder
    'limeBolder', 'redBolder', 'orangeBolder',
    'yellowBolder', 'greenBolder', 'tealBolder',
    'blueBolder', 'purpleBolder', 'magentaBolder',
    'grayBolder',
];

export const STATUS_PALETTE_GRADIENT = [
    'linear-gradient(135deg,#dddee1,#a8aab0)',
    'linear-gradient(135deg,#f6cef8,#b27ad7)',
    'linear-gradient(135deg,#cdd8fa,#5d7bf2)',
    'linear-gradient(135deg,#caedf6,#5fb8d6)',
    'linear-gradient(135deg,#caf3da,#5dbf83)',
    'linear-gradient(135deg,#facbe6,#e57aaa)',
];	